name: swagistan
favicon: null
layout_spectrum: 0.7404
typography_spectrum: 0.51688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4943de'
    - '#87cbde'
    - '#048bcd'
    - '#f75a94'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
